# Generated by Django 4.1.3 on 2023-02-10 04:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recommend',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('addr', models.CharField(max_length=255)),
                ('grade', models.FloatField(validators=[django.core.validators.MinValueValidator(0, 5), django.core.validators.MaxValueValidator(5.0)])),
                ('review', models.TextField()),
            ],
        ),
    ]
