# Generated by Django 4.1.4 on 2023-02-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_liverank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eatplace',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('review_star', models.TextField()),
                ('review_text', models.TextField()),
                ('gu', models.CharField(max_length=255)),
            ],
        ),
    ]
