# Generated by Django 4.1.4 on 2023-02-17 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pyspark',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='장소이름')),
                ('day', models.IntegerField(verbose_name='요일')),
                ('time', models.IntegerField(verbose_name='시간')),
                ('prediction', models.IntegerField(verbose_name='예측값')),
            ],
        ),
    ]
