# Generated by Django 4.1.4 on 2023-01-31 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='번호')),
                ('id', models.CharField(max_length=50, verbose_name='아이디')),
                ('pw', models.CharField(max_length=255, verbose_name='비밀번호')),
                ('name', models.CharField(max_length=30, verbose_name='이름')),
                ('nickname', models.CharField(max_length=10, verbose_name='닉네임')),
                ('email', models.CharField(max_length=50, verbose_name='이메일')),
                ('phone', models.CharField(max_length=13, verbose_name='전화번호')),
                ('addr0', models.CharField(default='charField', max_length=100, verbose_name='우편번호')),
                ('addr1', models.CharField(max_length=100, verbose_name='주소1')),
                ('addr2', models.CharField(max_length=100, verbose_name='주소2')),
                ('regdate', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('level', models.IntegerField(verbose_name='등급')),
                ('catePlace', models.CharField(max_length=10, verbose_name='선호하는 장소')),
                ('cateFood', models.CharField(max_length=10, verbose_name='선호하는 음식')),
            ],
        ),
    ]
