# Generated by Django 4.1.3 on 2023-02-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_member_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='level',
            field=models.IntegerField(null=True, verbose_name='등급'),
        ),
    ]
