# Generated by Django 4.1.4 on 2023-01-31 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False, verbose_name='글번호')),
                ('writer', models.CharField(max_length=50, verbose_name='작성자')),
                ('subject', models.CharField(max_length=300, verbose_name='글제목')),
                ('passwd', models.CharField(max_length=30, verbose_name='비밀번호')),
                ('content', models.TextField(verbose_name='글내용')),
                ('readcount', models.IntegerField(default=0, verbose_name='조회수')),
                ('ref', models.IntegerField(verbose_name='그룹화아이디')),
                ('restep', models.IntegerField(verbose_name='글순서')),
                ('relevel', models.IntegerField(verbose_name='글레벨')),
                ('regdate', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('ip', models.CharField(max_length=30, verbose_name='아이피')),
                ('id', models.CharField(max_length=50, verbose_name='아이디')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='댓글번호')),
                ('nick', models.CharField(max_length=50, verbose_name='닉네임')),
                ('comment', models.TextField(verbose_name='댓글')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('boardNum', models.IntegerField(null=True, verbose_name='게시글번호')),
            ],
        ),
        migrations.CreateModel(
            name='ImageBoard',
            fields=[
                ('imageid', models.AutoField(primary_key=True, serialize=False, verbose_name='아이디')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('image', models.ImageField(upload_to='images', verbose_name='이미지 경로')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='파일 이름')),
            ],
        ),
    ]
