# Generated by Django 4.1.4 on 2023-01-31 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('l_no', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=50)),
                ('p_no', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('p_no', models.AutoField(primary_key=True, serialize=False)),
                ('p_title', models.CharField(max_length=100)),
                ('p_nickname', models.CharField(max_length=50)),
                ('p_sdate', models.CharField(max_length=20)),
                ('p_edate', models.CharField(max_length=20, null=True)),
                ('p_days', models.IntegerField()),
                ('p_memo', models.TextField()),
                ('p_code', models.CharField(max_length=10)),
                ('p_content', models.CharField(max_length=200)),
                ('id', models.CharField(max_length=50)),
                ('day1', models.TextField()),
                ('day2', models.TextField()),
                ('day3', models.TextField()),
                ('day4', models.TextField()),
                ('day5', models.TextField()),
                ('day6', models.TextField()),
                ('day7', models.TextField()),
                ('addr', models.TextField()),
                ('place_name', models.TextField()),
                ('image', models.ImageField(upload_to='images', verbose_name='이미지 경로')),
                ('ref', models.IntegerField(verbose_name='그룹화아이디')),
                ('restep', models.IntegerField(verbose_name='글순서')),
            ],
        ),
        migrations.CreateModel(
            name='PlanComment',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='댓글번호')),
                ('nick', models.CharField(max_length=50, verbose_name='닉네임')),
                ('comment', models.TextField(verbose_name='댓글')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('boardNum', models.IntegerField(null=True, verbose_name='게시글번호')),
            ],
        ),
        migrations.CreateModel(
            name='PlanCount',
            fields=[
                ('c_no', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
                ('id', models.CharField(max_length=50)),
                ('p_no', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('p_no', models.AutoField(primary_key=True, serialize=False)),
                ('p_title', models.CharField(max_length=100)),
                ('p_nickname', models.CharField(max_length=50)),
                ('p_sdate', models.CharField(max_length=20)),
                ('p_edate', models.CharField(max_length=20, null=True)),
                ('p_days', models.IntegerField()),
                ('p_memo', models.TextField()),
                ('p_code', models.CharField(max_length=10)),
                ('p_content', models.CharField(max_length=200)),
                ('id', models.CharField(max_length=50)),
                ('day1', models.TextField()),
                ('day2', models.TextField()),
                ('day3', models.TextField()),
                ('day4', models.TextField()),
                ('day5', models.TextField()),
                ('day6', models.TextField()),
                ('day7', models.TextField()),
                ('addr', models.TextField()),
                ('image', models.ImageField(upload_to='images', verbose_name='이미지 경로')),
                ('ref', models.IntegerField(verbose_name='그룹화아이디')),
                ('restep', models.IntegerField(verbose_name='글순서')),
                ('plan_no', models.IntegerField()),
            ],
        ),
    ]
